version: "3.8"
services:
  app:
    build: .
    user: ${CURRENT_UID}
    environment:
      - TZ='America/Recife'
    working_dir: /app/
    volumes:
      - ./:/app/
    command: "npm run serve"
    ports:
      - 8061:8061