name: DEPLOY-DEV
on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js enviroment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x

      - uses: actions/checkout@v2

      - name: Install Firebase CLI globally
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: |
          cd src
          npm i
          npm install -g typescript

      - uses: actions/checkout@v2

      - name: Functions pre-deploy routine
        env:
          NUXT_ENV_NODE_ENV: dev
        run: |
          echo "$NUXT_ENV_NODE_ENV"
          rm -rf src/nuxt
          cd src
          npm i
          npm run build:dev
          cd ..
          rm -rf functions/lib
          mkdir -p functions/lib
          mkdir -p functions/lib/nuxt
          cp -r src/nuxt/ functions/lib
          cp src/nuxt.config.js functions/src
          cp src/nuxt.config.js functions/lib
          cd functions
          npm install
          tsc

      - name: Hosting pre-deploy routine
        run: |
          rm -rf public/*
          mkdir -p public/_nuxt
          cp -r src/nuxt/dist/client/. public/_nuxt
          cp -r src/static/. public/

      - name: Firebase Deploy
        run: |
          firebase use dev --token ${{ secrets.FIREBASE_TOKEN }}
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --only functions:ssrapp,hosting:dev.app
