# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [develop]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 14.x

      - name: Install Firebase CLI globally
        run: npm install -g firebase-tools

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          # The Java version to make available on the path. Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x). Early access versions can be specified in the form of e.g. 14-ea, 14.0.0-ea, or 14.0.0-ea.28
          java-version: 12.x

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: |
          cd functions
          npm install
          cd node_modules/$DD_TYPES_FNAME
          npm pack
          mv $DD_TYPES_FNAME-*.tgz ../../
          cd ../../
          npm i $DD_TYPES_FNAME-$DD_TYPES_VERSION.tgz
        env:
          DD_TYPES_FNAME: "deliverful-types"
          DD_TYPES_VERSION: "0.0.2"

      # May also run linting scripts
      - name: Test
        run: |
          cd functions
          firebase use default --token ${{ secrets.FIREBASE_TOKEN }}
          npm run test:cov -- --token ${{ secrets.FIREBASE_TOKEN }}

      # Runs a set of commands using the runners shell
      - name: Deploy
        run: |
          cd functions
          firebase use default --token ${{ secrets.FIREBASE_TOKEN }}
          npm run deploy -- --token ${{ secrets.FIREBASE_TOKEN }}
